services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566" # Edge port
      - "4510-4559:4510-4559" # Puertos internos (lambdas)
    environment:
      - SERVICES=lambda,logs,iam,sts,cloudwatch,events,apigateway,s3
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
      - PERSISTENCE=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

